networks:
  homework:
    driver: 'bridge'

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: homework-redis
    hostname: homework-redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    user: "root:root" # Note that Consul is run under the 'consul' user, but entry point scripts need to first run as root
    networks:
      - homework
    security_opt:
      - no-new-privileges:true
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: homework-postgresql
    hostname: homework-postgresql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
